# Generated by Django 6.0.2 on 2026-05-28 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0003_post_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='photo',
            old_name='Post',
            new_name='post',
        ),
    ]
