# Generated by Django 6.0.5 on 2026-06-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0004_rename_post_photo_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='image_file',
            field=models.ImageField(default='', upload_to=''),
            preserve_default=False,
        ),
    ]
