# Generated by Django 6.0.5 on 2026-06-16 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0002_book_author_book_book_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='page_num',
            field=models.TextField(default='none'),
            preserve_default=False,
        ),
    ]
