# Generated by Django 6.0.5 on 2026-06-23 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('BookClub', '0005_comment_reply'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='page_num',
            field=models.IntegerField(),
        ),
    ]
